steps:
  - label: ":cmake: Build & Test"
    plugins:
    - docker#v3.10.0:
        build: .
        shell: ["/bin/bash", "-e", "-c"]
    commands:
      - "cmake -S . -B build"
      - "cmake --build build"
      - "ctest --test-dir build"