steps:
  - label: ":cmake: Build & Test"
    plugins:
      - docker#v3.10.0:
          build:
            context: .
            dockerfile: Dockerfile
          shell: ["/bin/bash", "-e", "-c"]
    commands:
      - cmake -S . -B build
      - cmake --build build
      - cd build && ctest --verbose
