name: "CMake C++ Example"
description: "An example pipeline that builds and tests a C++ project using CMake."
emoji: ":cmake:"
languages:
  - "C++"
steps:
  - label: ":cmake: Build & Test"
    commands:
      - "cmake -S . -B build"
      - "cmake --build build"
      - "ctest --test-dir build"
